openapi: '3.1.0'
info:
  title: EventStreamsService
  version: 1.0.0
servers:
  - url: https://example.com/api
    description: Example service deployment.
paths:
  /greetings:
    post:
      operationId: getGreetingsStream
      parameters:
        - name: name
          required: false
          in: query
          description: The name used in the returned greeting.
          schema:
            type: string
      requestBody:
        description: A body with a greetings stream.
        required: true
        content:
          application/jsonl: {}
      responses:
        '200':
          description: A success response with a greetings stream.
          content:
            application/jsonl: {}
components:
  schemas:
    Greeting:
      type: object
      description: A value with the greeting contents.
      properties:
        message:
          type: string
          description: The string representation of the greeting.
      required:
        - message
